### Tensorflow

In [1]:
import tensorflow as tf

scalar = tf.constant(10)
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
scalar = tf.constant(10, dtype=tf.int64)
print(scalar)

tf.Tensor(10, shape=(), dtype=int64)


In [4]:
tf.print(scalar)

10


In [5]:
vector = [1,2,3,4,5,6,7]
vector_tensor = tf.constant(vector)
print(vector_tensor)

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [6]:
vector_tensor.ndim

1

In [7]:
vector_tensor.shape

TensorShape([7])

In [8]:
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [9]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [10]:
tf.size(vector_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
_tensor = [[[
    2,3,4,5,6
]]]
tensor = tf.constant(_tensor)

In [12]:
tensor

<tf.Tensor: shape=(1, 1, 5), dtype=int32, numpy=array([[[2, 3, 4, 5, 6]]], dtype=int32)>

In [14]:
_tensor = [
        [
            [2,3,4,5,6],
            [43,3,4,535,34]
        ],
        [
            [2,3,4,5,6],
            [43,3,4,535,34]
        ]
    ]
tensor = tf.constant(_tensor)
tf.print(tensor)
print(tensor)

[[[2 3 4 5 6]
  [43 3 4 535 34]]

 [[2 3 4 5 6]
  [43 3 4 535 34]]]
tf.Tensor(
[[[  2   3   4   5   6]
  [ 43   3   4 535  34]]

 [[  2   3   4   5   6]
  [ 43   3   4 535  34]]], shape=(2, 2, 5), dtype=int32)


*** NOTE *** 

If we need Single dimensional array, then we will use single opening and closing square brackets, value will go here
If we need 2 dimensional array, then we will use two opening and closing square brackets, value will go inside the second square brackets only
we create multi dimenttional array using this proccess.

[set[row[column]]]

In [15]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [16]:
_tensor = [
        [
            [2,3,4,5,6],
            [43,3,4,535,34, 34]
        ],
        [
            [2,3,4,5,6],
            [43,3,4,535,34]
        ]
    ]
tensor = tf.constant(_tensor)
tf.print(tensor)
print(tensor)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [17]:
scalar = tf.Variable(99)
print(scalar)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=99>


In [18]:
scalar.shape

TensorShape([])

In [19]:
vector = tf.Variable([32,4,3,434,34,34], dtype = tf.float64)

In [20]:
vector

<tf.Variable 'Variable:0' shape=(6,) dtype=float64, numpy=array([ 32.,   4.,   3., 434.,  34.,  34.])>

In [21]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [23]:
_tensor = [
        [
            [2,3,4,5,6],
            [43,3,4,535,34]
        ],
        [
            [2,3,4,5,6],
            [43,3,4,535,34]
        ]
    ]
tensor = tf.Variable(_tensor)
tf.print(tensor)
print(tensor)

[[[2 3 4 5 6]
  [43 3 4 535 34]]

 [[2 3 4 5 6]
  [43 3 4 535 34]]]
<tf.Variable 'Variable:0' shape=(2, 2, 5) dtype=int32, numpy=
array([[[  2,   3,   4,   5,   6],
        [ 43,   3,   4, 535,  34]],

       [[  2,   3,   4,   5,   6],
        [ 43,   3,   4, 535,  34]]], dtype=int32)>


In [24]:
tensor.shape

TensorShape([2, 2, 5])

In [25]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [26]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [30]:
constant_tensor = tf.constant([1,2,4,5,6,6,76,6])
print(constant_tensor)

tf.Tensor([ 1  2  4  5  6  6 76  6], shape=(8,), dtype=int32)


In [31]:
constant_tensor[1] = 3333

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [32]:
varialbe_tensor = tf.Variable([1,2,4,5,6,6,76,6])
print(varialbe_tensor)

<tf.Variable 'Variable:0' shape=(8,) dtype=int32, numpy=array([ 1,  2,  4,  5,  6,  6, 76,  6], dtype=int32)>


In [33]:
varialbe_tensor[1] = 10000

TypeError: 'ResourceVariable' object does not support item assignment

In [35]:
varialbe_tensor[1].assign(1000)

<tf.Variable 'UnreadVariable' shape=(8,) dtype=int32, numpy=array([   1, 1000,    4,    5,    6,    6,   76,    6], dtype=int32)>