In [1]:
import tensorflow as tf

In [2]:
tf.one_hot([3,2,0,4], 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [7]:
tf.one_hot([3,2,0,4, 1], 4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [8]:
tf.keras.utils.to_categorical([0,3,2,1], 4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [ ]:
tf.keras.utils.to_categorical([0,3,2,1, 6], 4)

IndexError: index 6 is out of bounds for axis 1 with size 4

In [10]:
tf.keras.utils.to_categorical([0,3,2,1, 2], 4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])