In [1]:
import tensorflow as tf

In [2]:
range_vector = tf.range(11)

In [3]:
for i in range_vector:
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [4]:
sum_vector = 0
for i in range_vector:
    sum_vector += i

print(sum_vector)

tf.Tensor(55, shape=(), dtype=int32)


In [5]:
range_vector.consumers

<bound method _EagerTensorBase.consumers of <tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>>

In [8]:
sum_vector/tf.size(range_vector)

<tf.Tensor: shape=(), dtype=float64, numpy=5.0>

In [11]:
print(tf.add(range_vector, 11))
print(tf.multiply(range_vector, 2))


tf.Tensor([11 12 13 14 15 16 17 18 19 20 21], shape=(11,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18 20], shape=(11,), dtype=int32)


In [12]:
sum = tf.reduce_sum(range_vector)

In [13]:
sum

<tf.Tensor: shape=(), dtype=int32, numpy=55>

In [14]:
average = tf.reduce_mean(range_vector)

In [15]:
average

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [16]:
sum_of_square = 0

for index, value in enumerate(range_vector):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 0
Index: 1, Value: 1
Index: 2, Value: 2
Index: 3, Value: 3
Index: 4, Value: 4
Index: 5, Value: 5
Index: 6, Value: 6
Index: 7, Value: 7
Index: 8, Value: 8
Index: 9, Value: 9
Index: 10, Value: 10


In [ ]:
for index in range_vector:
    sum_of_square += tf.math.square(range_vector[index] - average)
    print(sum_of_square)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(41, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(54, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(56, shape=(), dtype=int32)
tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor(69, shape=(), dtype=int32)
tf.Tensor(85, shape=(), dtype=int32)
tf.Tensor(110, shape=(), dtype=int32)


In [18]:
standard_variance = tf.math.sqrt(sum_of_square / tf.size(range_vector))
print(standard_variance)

tf.Tensor(3.1622776601683795, shape=(), dtype=float64)


In [20]:
print(tf.math.reduce_mean(range_vector))
print(tf.math.reduce_std(tf.cast(range_vector, tf.float32)))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(3.1622777, shape=(), dtype=float32)


In [21]:
random_normal = tf.random.normal((2,3), 50, 10)
print(random_normal)

tf.Tensor(
[[60.997337 56.23383  63.761208]
 [51.283005 54.37789  28.276302]], shape=(2, 3), dtype=float32)


In [22]:
print(tf.math.reduce_mean(random_normal))
print(tf.math.reduce_std(tf.cast(random_normal, tf.float32)))

tf.Tensor(52.488262, shape=(), dtype=float32)
tf.Tensor(11.581272, shape=(), dtype=float32)


In [27]:
uniform_tensor = tf.random.uniform((2,3,4,5), 10, 20)
print(uniform_tensor)

tf.Tensor(
[[[[13.898455  18.902388  10.377203  16.591911  12.951417 ]
   [14.30256   16.843033  12.2762165 10.58066   16.098251 ]
   [14.846081  12.71454   11.164457  12.321258  15.846079 ]
   [12.664623  11.621811  14.658574  11.16618   18.83236  ]]

  [[16.977776  17.666029  10.908644  15.411754  17.439316 ]
   [15.901298  19.773624  11.739653  19.401115  14.529538 ]
   [19.9267    19.771994  15.911656  19.181965  13.200165 ]
   [13.284706  19.469448  15.35356   18.179892  15.711361 ]]

  [[10.594483  17.705378  18.390192  18.672562  11.460575 ]
   [12.106046  10.75894   17.86127   10.140089  12.849847 ]
   [18.683392  17.825089  18.34789   14.609201  19.136492 ]
   [10.662714  19.062246  15.316795  11.42538   19.875175 ]]]


 [[[11.61286   12.083828  19.728367  15.898343  15.100813 ]
   [12.275687  11.425971  12.286777  10.954859  13.719636 ]
   [17.221577  14.25515   14.18544   14.820826  19.962555 ]
   [18.129402  17.524     14.8328285 16.482193  18.145813 ]]

  [[16.618328  14.3

In [28]:
print(tf.math.reduce_mean(uniform_tensor))
print(tf.math.reduce_std(tf.cast(uniform_tensor, tf.float32)))

tf.Tensor(15.183536, shape=(), dtype=float32)
tf.Tensor(2.9531274, shape=(), dtype=float32)


In [29]:
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12],
    [13,14,15]
])
print(matrix)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]], shape=(5, 3), dtype=int32)


In [31]:
print(tf.random.shuffle(matrix))
print(matrix)

tf.Tensor(
[[10 11 12]
 [ 4  5  6]
 [13 14 15]
 [ 7  8  9]
 [ 1  2  3]], shape=(5, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]], shape=(5, 3), dtype=int32)


In [32]:
print(tf.reshape(matrix, (3,5)))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]], shape=(3, 5), dtype=int32)


In [33]:
print(tf.reshape(matrix, -1))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(15,), dtype=int32)


In [34]:
print(tf.cast(matrix, tf.float64))

tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]], shape=(5, 3), dtype=float64)


In [35]:
tensor_2d = tf.random.uniform((2,3), 10, 20)
print(tensor_2d)

tf.Tensor(
[[10.894517 16.036592 12.037297]
 [16.491737 12.9353   18.47668 ]], shape=(2, 3), dtype=float32)


In [36]:
tensor_2d.ndim

2

In [37]:
tensor_2d[1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=18.476680755615234>

In [39]:
tensor_2d[0,0:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10.894517, 16.036592, 12.037297], dtype=float32)>

In [40]:
tensor_2d[0:,0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.894517, 16.491737], dtype=float32)>

In [41]:
scalar_a = 100
scalar_b = 200
tf.add(scalar_a, scalar_b)

<tf.Tensor: shape=(), dtype=int32, numpy=300>

In [42]:
tf.multiply(scalar_a, scalar_b)

<tf.Tensor: shape=(), dtype=int32, numpy=20000>

In [43]:
vector_a = tf.range(10)
vector_b = tf.range(20, 30)

In [44]:
vector_a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [45]:
vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

In [46]:
vector_a + vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38], dtype=int32)>

In [47]:
tf.add(vector_a , vector_b)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38], dtype=int32)>

In [48]:
tf.multiply(vector_a , vector_b)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261], dtype=int32)>

In [49]:
vector_a * vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261], dtype=int32)>

In [50]:
tensor_a = tf.random.normal((2,3,4,5), 50, 10)
tensor_b = tf.random.normal((2,3,4,5), 100, 50)

In [52]:
print(tensor_a)
print(tensor_b)
print(tf.add(tensor_a, tensor_b))
print(tf.multiply(tensor_a, tensor_b))

tf.Tensor(
[[[[59.98208  56.263527 37.351215 62.852196 54.76448 ]
   [59.467785 45.73865  43.344666 46.85186  62.917255]
   [62.33086  47.750126 50.780365 60.53624  45.611755]
   [61.982555 79.8418   48.222534 67.34451  51.87873 ]]

  [[64.043846 47.13301  38.423264 50.909042 73.66613 ]
   [38.280865 55.72748  53.49733  39.016193 41.39796 ]
   [52.600105 45.850273 50.351513 33.42475  48.636795]
   [50.700294 62.529106 54.578526 51.500572 39.532124]]

  [[51.83207  53.903625 82.41806  34.55648  55.11888 ]
   [46.48415  51.42568  44.70702  61.62363  64.58887 ]
   [49.85373  48.521957 40.08443  41.12671  56.277607]
   [55.466366 48.3982   61.839695 47.643787 43.73953 ]]]


 [[[59.65933  29.482271 53.312443 45.86061  56.68495 ]
   [44.444885 48.57739  36.226616 33.209595 56.220467]
   [57.17361  43.07244  50.52222  59.19875  40.38254 ]
   [32.797386 76.36414  54.223675 37.225113 46.19421 ]]

  [[71.80938  60.194607 42.34681  39.375317 43.787827]
   [40.691032 42.70043  20.966452 59.423622 

In [54]:
print(tf.reduce_min(tensor_a))

tf.Tensor(20.966452, shape=(), dtype=float32)


In [55]:
print(tf.reduce_max(tensor_a))

tf.Tensor(82.41806, shape=(), dtype=float32)


In [56]:
print(tf.reduce_mean(tensor_a))

tf.Tensor(50.66743, shape=(), dtype=float32)


In [57]:
print(tf.math.reduce_std(tensor_a))

tf.Tensor(10.603056, shape=(), dtype=float32)


In [58]:
print(tf.reduce_sum(tensor_a))

tf.Tensor(6080.092, shape=(), dtype=float32)


In [59]:
print(tf.square(tensor_a))

tf.Tensor(
[[[[3597.8499 3165.5845 1395.1133 3950.3984 2999.1484]
   [3536.4175 2092.0242 1878.76   2195.0967 3958.581 ]
   [3885.1362 2280.0745 2578.6455 3664.6362 2080.4321]
   [3841.8372 6374.7124 2325.4128 4535.283  2691.4026]]

  [[4101.6143 2221.5208 1476.3472 2591.7307 5426.6987]
   [1465.4246 3105.5522 2861.9644 1522.2633 1713.7911]
   [2766.771  2102.2476 2535.275  1117.214  2365.5378]
   [2570.5198 3909.8892 2978.8154 2652.3088 1562.7888]]

  [[2686.5635 2905.6008 6792.737  1194.1504 3038.091 ]
   [2160.7761 2644.6003 1998.7177 3797.472  4171.7217]
   [2485.3943 2354.3804 1606.7616 1691.4062 3167.169 ]
   [3076.5178 2342.3857 3824.148  2269.9304 1913.1464]]]


 [[[3559.2354  869.2043 2842.2166 2103.1956 3213.1838]
   [1975.3478 2359.7627 1312.3677 1102.8772 3160.741 ]
   [3268.8218 1855.2352 2552.4949 3504.492  1630.7496]
   [1075.6686 5831.4824 2940.2068 1385.709  2133.905 ]]

  [[5156.587  3623.3906 1793.2523 1550.4155 1917.3738]
   [1655.7601 1823.3269  439.5921 3531.1667 

In [60]:
print(tf.round(tensor_a))

tf.Tensor(
[[[[60. 56. 37. 63. 55.]
   [59. 46. 43. 47. 63.]
   [62. 48. 51. 61. 46.]
   [62. 80. 48. 67. 52.]]

  [[64. 47. 38. 51. 74.]
   [38. 56. 53. 39. 41.]
   [53. 46. 50. 33. 49.]
   [51. 63. 55. 52. 40.]]

  [[52. 54. 82. 35. 55.]
   [46. 51. 45. 62. 65.]
   [50. 49. 40. 41. 56.]
   [55. 48. 62. 48. 44.]]]


 [[[60. 29. 53. 46. 57.]
   [44. 49. 36. 33. 56.]
   [57. 43. 51. 59. 40.]
   [33. 76. 54. 37. 46.]]

  [[72. 60. 42. 39. 44.]
   [41. 43. 21. 59. 63.]
   [45. 75. 44. 36. 43.]
   [41. 47. 51. 34. 54.]]

  [[43. 45. 43. 54. 48.]
   [58. 38. 60. 65. 44.]
   [46. 63. 48. 50. 50.]
   [49. 57. 49. 56. 61.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [62]:
print(tf.math.ceil(tensor_a))

tf.Tensor(
[[[[60. 57. 38. 63. 55.]
   [60. 46. 44. 47. 63.]
   [63. 48. 51. 61. 46.]
   [62. 80. 49. 68. 52.]]

  [[65. 48. 39. 51. 74.]
   [39. 56. 54. 40. 42.]
   [53. 46. 51. 34. 49.]
   [51. 63. 55. 52. 40.]]

  [[52. 54. 83. 35. 56.]
   [47. 52. 45. 62. 65.]
   [50. 49. 41. 42. 57.]
   [56. 49. 62. 48. 44.]]]


 [[[60. 30. 54. 46. 57.]
   [45. 49. 37. 34. 57.]
   [58. 44. 51. 60. 41.]
   [33. 77. 55. 38. 47.]]

  [[72. 61. 43. 40. 44.]
   [41. 43. 21. 60. 64.]
   [46. 76. 45. 36. 43.]
   [41. 48. 52. 35. 54.]]

  [[44. 46. 44. 55. 48.]
   [59. 38. 61. 65. 44.]
   [46. 64. 48. 51. 50.]
   [49. 57. 49. 56. 62.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [63]:
print(tf.math.floor(tensor_a))

tf.Tensor(
[[[[59. 56. 37. 62. 54.]
   [59. 45. 43. 46. 62.]
   [62. 47. 50. 60. 45.]
   [61. 79. 48. 67. 51.]]

  [[64. 47. 38. 50. 73.]
   [38. 55. 53. 39. 41.]
   [52. 45. 50. 33. 48.]
   [50. 62. 54. 51. 39.]]

  [[51. 53. 82. 34. 55.]
   [46. 51. 44. 61. 64.]
   [49. 48. 40. 41. 56.]
   [55. 48. 61. 47. 43.]]]


 [[[59. 29. 53. 45. 56.]
   [44. 48. 36. 33. 56.]
   [57. 43. 50. 59. 40.]
   [32. 76. 54. 37. 46.]]

  [[71. 60. 42. 39. 43.]
   [40. 42. 20. 59. 63.]
   [45. 75. 44. 35. 42.]
   [40. 47. 51. 34. 53.]]

  [[43. 45. 43. 54. 47.]
   [58. 37. 60. 64. 43.]
   [45. 63. 47. 50. 49.]
   [48. 56. 48. 55. 61.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [64]:
tf.math.argmax(tensor_a)

<tf.Tensor: shape=(3, 4, 5), dtype=int64, numpy=
array([[[0, 0, 1, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]],

       [[1, 1, 1, 0, 0],
        [1, 0, 0, 1, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[0, 0, 0, 1, 0],
        [1, 0, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 0, 1, 1]]])>

In [66]:
matrix = tf.random.normal((2,3), 50, 10)

In [67]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[32.1977  , 60.108585, 36.897503],
       [48.94785 , 43.482323, 40.56325 ]], dtype=float32)>

In [68]:
tf.math.argmax(matrix)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 1])>

In [70]:
matrix[0, 1]

<tf.Tensor: shape=(), dtype=float32, numpy=60.108585357666016>

In [71]:
tf.math.argmax(matrix, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [72]:
tf.math.argmin(matrix)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 0])>

In [73]:
tf.math.argmin(matrix, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 2])>

In [74]:
tf.math.equal(tensor_a, tensor_b)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=bool, numpy=
array([[[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]],


       [[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, 

In [75]:
tf.math.equal(tf.math.floor(tensor_a), tf.math.floor(tensor_b))

<tf.Tensor: shape=(2, 3, 4, 5), dtype=bool, numpy=
array([[[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]],


       [[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, 

In [76]:
tf.math.not_equal(tf.math.floor(tensor_a), tf.math.floor(tensor_b))

<tf.Tensor: shape=(2, 3, 4, 5), dtype=bool, numpy=
array([[[[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]],


       [[[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True, 

In [77]:
tf.math.greater(tensor_a ,tensor_b)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=bool, numpy=
array([[[[False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [ True, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False,  True, False],
         [False, False, False, False, False],
         [False,  True, False, False, False]]],


       [[[False,  True, False, False,  True],
         [False, False, False, False, False],
         [False,  True, False, False, False],
         [False, False, False, False,  True]],

        [[False, False, False, False, False],
         [False,  True, False, False, False],
         [False, False, False, False,  True],
         [False, False, False, False,  True]],

        [[False, 

In [78]:
tf.math.greater_equal(tensor_a ,tensor_b)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=bool, numpy=
array([[[[False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [ True, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False,  True, False],
         [False, False, False, False, False],
         [False,  True, False, False, False]]],


       [[[False,  True, False, False,  True],
         [False, False, False, False, False],
         [False,  True, False, False, False],
         [False, False, False, False,  True]],

        [[False, False, False, False, False],
         [False,  True, False, False, False],
         [False, False, False, False,  True],
         [False, False, False, False,  True]],

        [[False, 

In [79]:
tf.math.reduce_prod(tensor_a)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [80]:
tf.math.reduce_prod(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=6165062656.0>

In [81]:
tf.math.reduce_variance(tensor_a)

<tf.Tensor: shape=(), dtype=float32, numpy=112.42478942871094>

In [84]:
print(tf.math.reduce_variance(tf.cast(matrix, tf.float32)))

tf.Tensor(80.87417, shape=(), dtype=float32)


In [85]:
print(tf.math.reduce_variance(tf.cast(tensor_a, tf.float32)))

tf.Tensor(112.42479, shape=(), dtype=float32)


In [89]:
tensor_a @ tensor_b

InvalidArgumentError: {{function_node __wrapped____MklBatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3,4,5], In[1]: [2,3,4,5] 0 0 [Op:BatchMatMulV2] name: 

In [90]:
tensor_a @ tf.reshape(tensor_b, (5,-1))

<tf.Tensor: shape=(2, 3, 4, 24), dtype=float32, numpy=
array([[[[28325.094 , 30280.232 , 36254.79  , 26006.686 , 36526.883 ,
          28078.22  , 22151.83  , 14829.499 , 16342.815 , 32892.44  ,
          29912.037 , 30363.33  , 30836.797 , 27749.    , 15923.564 ,
          28871.42  , 21047.287 , 38772.727 , 32869.016 , 29377.027 ,
          28328.07  , 30305.865 , 20196.154 , 28942.602 ],
         [26179.145 , 29982.928 , 36113.082 , 23279.146 , 33360.71  ,
          25778.348 , 21134.316 , 14791.258 , 14529.044 , 31036.457 ,
          26945.03  , 29869.732 , 28897.336 , 25823.46  , 15971.705 ,
          28926.479 , 19627.574 , 37738.152 , 32146.99  , 28082.043 ,
          26689.535 , 27689.475 , 19958.555 , 28261.465 ],
         [26746.803 , 28797.902 , 35867.17  , 26068.248 , 37370.87  ,
          27707.553 , 22364.057 , 16404.885 , 14288.417 , 33217.195 ,
          30517.262 , 29734.434 , 29221.967 , 25425.557 , 15967.3125,
          30134.117 , 19962.66  , 37744.445 , 33628.254 ,

In [92]:
tf.linalg.matmul(tensor_a , tf.reshape(tensor_b, (5,-1)))

<tf.Tensor: shape=(2, 3, 4, 24), dtype=float32, numpy=
array([[[[28325.094 , 30280.232 , 36254.79  , 26006.686 , 36526.883 ,
          28078.22  , 22151.83  , 14829.499 , 16342.815 , 32892.44  ,
          29912.037 , 30363.33  , 30836.797 , 27749.    , 15923.564 ,
          28871.42  , 21047.287 , 38772.727 , 32869.016 , 29377.027 ,
          28328.07  , 30305.865 , 20196.154 , 28942.602 ],
         [26179.145 , 29982.928 , 36113.082 , 23279.146 , 33360.71  ,
          25778.348 , 21134.316 , 14791.258 , 14529.044 , 31036.457 ,
          26945.03  , 29869.732 , 28897.336 , 25823.46  , 15971.705 ,
          28926.479 , 19627.574 , 37738.152 , 32146.99  , 28082.043 ,
          26689.535 , 27689.475 , 19958.555 , 28261.465 ],
         [26746.803 , 28797.902 , 35867.17  , 26068.248 , 37370.87  ,
          27707.553 , 22364.057 , 16404.885 , 14288.417 , 33217.195 ,
          30517.262 , 29734.434 , 29221.967 , 25425.557 , 15967.3125,
          30134.117 , 19962.66  , 37744.445 , 33628.254 ,

In [93]:
tf.transpose(matrix)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[32.1977  , 48.94785 ],
       [60.108585, 43.482323],
       [36.897503, 40.56325 ]], dtype=float32)>

In [97]:
tf.split(matrix, num_or_size_splits=2)

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[32.1977  , 60.108585, 36.897503]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[48.94785 , 43.482323, 40.56325 ]], dtype=float32)>]

In [99]:
tf.split(matrix, num_or_size_splits=3, axis=1)

[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[32.1977 ],
        [48.94785]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[60.108585],
        [43.482323]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[36.897503],
        [40.56325 ]], dtype=float32)>]

In [100]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[32.1977  , 60.108585, 36.897503],
       [48.94785 , 43.482323, 40.56325 ]], dtype=float32)>

In [103]:
tf.reverse(matrix, axis=[0,1])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[40.56325 , 43.482323, 48.94785 ],
       [36.897503, 60.108585, 32.1977  ]], dtype=float32)>