### Image read and show also understand numpyImage 

In [ ]:
import cv2
img = cv2.imread("uttam.jpg")
cv2.imshow("Image of Developer", img)
cv2.imwrite("saveimage.png", img)
cv2.waitKey(0)
if ord('q'):
    quit()

cv2.destroyAllWindows()

: 

In [1]:
import cv2
img = cv2.imread("uttam.jpg")
print(type(img))
print(img.size)
print(img.shape)

<class 'numpy.ndarray'>
3745320
(1058, 1180, 3)


In [2]:
height, width, channel = img.shape

In [3]:
print(height)
print(width)
print(channel)

1058
1180
3


In [4]:
print(img.ndim)

3


In [5]:
print(img[0:, 0, 0])

[ 47  47  48 ... 106 105 105]


In [6]:
print(img[0:, 0, 0:])

[[ 47  67  68]
 [ 47  67  68]
 [ 48  68  69]
 ...
 [106 120 119]
 [105 119 118]
 [105 119 118]]


In [7]:
print(img[0, 0:, 0:])

[[ 47  67  68]
 [ 47  67  68]
 [ 48  68  69]
 ...
 [ 81 119 137]
 [ 80 118 136]
 [ 79 117 135]]


In [12]:
height = img[0:, 0, 0]
print(height)

[ 47  47  48 ... 106 105 105]


In [8]:
B = img[0:, 0:, 0]
G = img[0:, 0:, 1]
R = img[0:, 0:, 2]
print(R)

[[ 68  68  69 ... 137 136 135]
 [ 68  68  69 ... 136 135 134]
 [ 69  69  69 ... 132 131 130]
 ...
 [119 118 116 ... 117 117 117]
 [118 118 118 ... 116 116 116]
 [118 118 118 ... 116 116 116]]


In [9]:
G

array([[ 67,  67,  68, ..., 119, 118, 117],
       [ 67,  67,  68, ..., 118, 117, 116],
       [ 68,  68,  68, ..., 117, 116, 115],
       ...,
       [120, 119, 117, ..., 114, 114, 114],
       [119, 119, 119, ..., 113, 113, 113],
       [119, 119, 119, ..., 113, 113, 113]],
      shape=(1058, 1180), dtype=uint8)

In [10]:
B

array([[ 47,  47,  48, ...,  81,  80,  79],
       [ 47,  47,  48, ...,  80,  79,  78],
       [ 48,  48,  48, ...,  78,  77,  76],
       ...,
       [106, 105, 103, ...,  97,  97,  97],
       [105, 105, 105, ...,  96,  96,  96],
       [105, 105, 105, ...,  96,  96,  96]],
      shape=(1058, 1180), dtype=uint8)

In [ ]:
import cv2
cv2.imshow("Red Image", R)
cv2.imshow("Green Image", G)
cv2.imshow("Blue Image", B)
cv2.imwrite("Rimage.png", R)
cv2.imwrite("Gimage.png", G)
cv2.imwrite("Bimage.png", B)
cv2.waitKey(0)
if ord('q'):
    quit()

cv2.destroyAllWindows()

: 