### Indexing and Slicing

In [1]:
import numpy as np

In [ ]:
np_array = np.arange(1,20)

In [4]:
print(np_array[4])

5


In [6]:
print(np_array[3:9])
print(np_array[:9])
print(np_array[9:])

[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [7]:
twoD = np.random.normal(100, 10, size=(10,10))

In [8]:
print(twoD)
print(twoD[2])
print(twoD[2][3])

[[ 92.43314051  89.95203803 109.25856167 104.10885627  87.21080629
  104.03801493  89.49319641 100.74350749 108.66633681  99.49066093]
 [ 91.85965618  86.77642278  76.73776077 104.63647426 102.68157935
  115.86424134 100.2310182  100.68144145 112.03009018  89.08481719]
 [ 85.6430705  101.03914024  94.41684849 104.67078426 108.4182562
  102.30872611 111.60745805 114.9267616  106.69693371  94.92528636]
 [110.29689622  95.23157456  90.37331859 107.99364039 101.58382625
  104.76534905 111.56792712 101.98818635 112.2896476  103.24642884]
 [ 91.3431316  110.65166561 121.84860848 113.17662091 104.0106494
  113.76895366  89.83576222 131.52684127  93.71005633 104.68630512]
 [ 85.06844926  85.7945514   90.30741802  75.99923448 109.23946975
   94.43784351  97.35183266  99.7361252   92.30902881  99.22481235]
 [ 92.42554599  94.97757148  94.67208757  94.67154074  97.0056905
   93.1575583  116.44861238  99.12932099 112.59492896  93.21555408]
 [ 91.37013644  96.40200539  88.10899396  99.17945941 104.

In [9]:
print(twoD[2,3])

104.67078426155433


In [10]:
print(twoD[2,1:6])

[101.03914024  94.41684849 104.67078426 108.4182562  102.30872611]


In [12]:
print(twoD[2:6,1:6])

[[101.03914024  94.41684849 104.67078426 108.4182562  102.30872611]
 [ 95.23157456  90.37331859 107.99364039 101.58382625 104.76534905]
 [110.65166561 121.84860848 113.17662091 104.0106494  113.76895366]
 [ 85.7945514   90.30741802  75.99923448 109.23946975  94.43784351]]


In [13]:
twoD[1:-1,1:-1] = 0
print(twoD)

[[ 92.43314051  89.95203803 109.25856167 104.10885627  87.21080629
  104.03801493  89.49319641 100.74350749 108.66633681  99.49066093]
 [ 91.85965618   0.           0.           0.           0.
    0.           0.           0.           0.          89.08481719]
 [ 85.6430705    0.           0.           0.           0.
    0.           0.           0.           0.          94.92528636]
 [110.29689622   0.           0.           0.           0.
    0.           0.           0.           0.         103.24642884]
 [ 91.3431316    0.           0.           0.           0.
    0.           0.           0.           0.         104.68630512]
 [ 85.06844926   0.           0.           0.           0.
    0.           0.           0.           0.          99.22481235]
 [ 92.42554599   0.           0.           0.           0.
    0.           0.           0.           0.          93.21555408]
 [ 91.37013644   0.           0.           0.           0.
    0.           0.           0.           0

### Copy and View

In [14]:
main_np_arr = np.eye(10)

In [15]:
print(main_np_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [16]:
view_np_arr = main_np_arr.view()
print(view_np_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
view_np_arr[0, 0:] = 99

In [18]:
print(main_np_arr)
print(view_np_arr)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [19]:
view_arr2 = main_np_arr
view_arr2[1, 1:] = 88

In [20]:
print(view_arr2)
print(main_np_arr)
print(view_np_arr)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.

In [21]:
copy_arr = main_np_arr.copy()

print(copy_arr)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [22]:
print(main_np_arr)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [23]:
copy_arr[2, 2:] = 77

In [24]:
print(copy_arr)
print(view_arr2)
print(main_np_arr)
print(view_np_arr)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0. 77. 77. 77. 77. 77. 77. 77. 77.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 88. 88. 88. 88. 88. 88. 88. 88. 88.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.

### Reshape, Resize, Ravel & Flatten

In [25]:
old_array = np.eye(3,6)
print(old_array)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [26]:
old_array.reshape(6,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
old_array.reshape(4,4)

ValueError: cannot reshape array of size 18 into shape (4,4)

In [28]:
print(old_array)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [29]:
old_array.resize(6,3)

In [30]:
print(old_array)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [31]:
old_array.ravel()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])

In [32]:
print(old_array)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [33]:
old_array.flatten()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])

In [34]:
print(old_array)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [35]:
ravel_arr = old_array.ravel()

In [36]:
print(ravel_arr)

[1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [37]:
print(old_array)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [38]:
old_array[1, 0:] = 111
print(old_array)
print(ravel_arr)

[[  1.   0.   0.]
 [111. 111. 111.]
 [  0.   1.   0.]
 [  0.   0.   0.]
 [  0.   0.   1.]
 [  0.   0.   0.]]
[  1.   0.   0. 111. 111. 111.   0.   1.   0.   0.   0.   0.   0.   0.
   1.   0.   0.   0.]


In [39]:
print(old_array)
flatten_arr = old_array.flatten()
print(flatten_arr)

[[  1.   0.   0.]
 [111. 111. 111.]
 [  0.   1.   0.]
 [  0.   0.   0.]
 [  0.   0.   1.]
 [  0.   0.   0.]]
[  1.   0.   0. 111. 111. 111.   0.   1.   0.   0.   0.   0.   0.   0.
   1.   0.   0.   0.]


In [40]:
old_array[2, 0:] = 333

In [42]:
print(old_array)
print(flatten_arr)
print(ravel_arr)

[[  1.   0.   0.]
 [111. 111. 111.]
 [333. 333. 333.]
 [  0.   0.   0.]
 [  0.   0.   1.]
 [  0.   0.   0.]]
[  1.   0.   0. 111. 111. 111.   0.   1.   0.   0.   0.   0.   0.   0.
   1.   0.   0.   0.]
[  1.   0.   0. 111. 111. 111. 333. 333. 333.   0.   0.   0.   0.   0.
   1.   0.   0.   0.]


### Arithmetic Operations & Aggregations

In [43]:
print(main_np_arr + old_array + np_array)

ValueError: operands could not be broadcast together with shapes (10,10) (6,3) 

In [49]:
arr1 = np.ones([3,6])
arr2 = np.random.normal(10, 5, size=(3,6))

In [50]:
print(arr1 + arr2)

[[14.57100249 12.9058458   7.16025564 19.70398404 11.11303662  9.93232759]
 [11.31225793  6.66210987  9.4726182   8.25955957 18.02271344 20.19924803]
 [18.15775796  2.51976766 10.18079955 19.6179868   8.62714503 10.17700725]]


In [51]:
np.add(arr1, arr2)

array([[14.57100249, 12.9058458 ,  7.16025564, 19.70398404, 11.11303662,
         9.93232759],
       [11.31225793,  6.66210987,  9.4726182 ,  8.25955957, 18.02271344,
        20.19924803],
       [18.15775796,  2.51976766, 10.18079955, 19.6179868 ,  8.62714503,
        10.17700725]])

In [52]:
print(arr1 * arr2)

[[13.57100249 11.9058458   6.16025564 18.70398404 10.11303662  8.93232759]
 [10.31225793  5.66210987  8.4726182   7.25955957 17.02271344 19.19924803]
 [17.15775796  1.51976766  9.18079955 18.6179868   7.62714503  9.17700725]]


In [53]:
np.multiply(arr1, arr2)

array([[13.57100249, 11.9058458 ,  6.16025564, 18.70398404, 10.11303662,
         8.93232759],
       [10.31225793,  5.66210987,  8.4726182 ,  7.25955957, 17.02271344,
        19.19924803],
       [17.15775796,  1.51976766,  9.18079955, 18.6179868 ,  7.62714503,
         9.17700725]])

In [54]:
arr2.sum()

np.float64(200.59542346864998)

In [55]:
print(arr2.mean())
print(arr2.std())
print(arr2.prod())
print(arr2.var())
print(arr2.cumsum())
print(arr2.min())
print(arr2.max())

11.144190192702776
5.008734915488574
6.157980066396659e+17
25.08742545363433
[ 13.57100249  25.47684829  31.63710393  50.34108796  60.45412459
  69.38645218  79.69871011  85.36081998  93.83343818 101.09299775
 118.11571119 137.31495922 154.47271717 155.99248483 165.17328438
 183.79127118 191.41841622 200.59542347]
1.5197676587422464
19.19924802613718


In [56]:
np.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
import numpy as np
arr2 = np.random.normal(10, 5, size=(3,6))
arr2.reshape(6,3)
arr2.reshape(9,2)
arr2.resize(6,3)
arr2.resize(2,9)