In [2]:
import numpy as np

In [4]:
np.array([1,2,3,4,5,6,7,8,9,10], dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.empty(10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.empty([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [10]:
np.eye(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [15]:
np.zeros(10)
np.zeros((5, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((5,6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [20]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
np.random.rand(10)

array([0.81336757, 0.65140898, 0.33339258, 0.51083222, 0.09346352,
       0.2740613 , 0.6554287 , 0.6721803 , 0.86923615, 0.408203  ])

In [22]:
np.random.rand(3,4)

array([[0.44083618, 0.96296376, 0.62072719, 0.55061115],
       [0.62209424, 0.50241562, 0.55665784, 0.09043929],
       [0.22518835, 0.62378224, 0.63952895, 0.08084307]])

In [23]:
np.random.randint(10, 30, size=(5,5))

array([[20, 14, 18, 18, 12],
       [18, 10, 13, 27, 11],
       [13, 24, 25, 24, 26],
       [24, 23, 17, 18, 18],
       [29, 24, 23, 15, 13]], dtype=int32)

In [24]:
np.random.sample(size=(4,6))

array([[0.88863945, 0.91131635, 0.46333885, 0.8193394 , 0.90773967,
        0.39767863],
       [0.83314125, 0.01990758, 0.37077511, 0.38614297, 0.91370015,
        0.45624871],
       [0.73915281, 0.22877349, 0.82016816, 0.8264649 , 0.82358654,
        0.70028372],
       [0.22181269, 0.4182771 , 0.72808643, 0.90279984, 0.99396602,
        0.00701964]])

In [25]:
np.random.normal(50, 5, size=(4,6))

array([[48.13592631, 41.5390736 , 59.06162813, 49.67427418, 53.04394461,
        43.15279772],
       [48.35315897, 49.53777103, 53.55855445, 42.02595973, 49.64144731,
        53.77245711],
       [57.86041419, 50.983312  , 54.89076   , 44.75864676, 55.09333611,
        47.66343059],
       [41.12947843, 43.89628219, 49.73994984, 47.13827195, 48.33849358,
        44.8950868 ]])