In [15]:
import numpy as np

In [16]:
ar1 = np.array([12,23,34,45,55], dtype=float)
ar2 = np.eye(3,6, dtype=int)
ar3 = np.arange(10,21,3)
ar4 = np.random.normal(50,5, size=(3,6))

In [17]:
ar1.ndim

1

In [18]:
ar2.ndim

2

In [19]:
ar3.size

4

In [20]:
ar4.size

18

In [21]:
ar2.shape

(3, 6)

In [22]:
ar4.dtype

dtype('float64')

In [23]:
print(ar4)

[[49.14024435 53.14240734 51.3191944  47.30454397 59.85420567 49.16588355]
 [49.34184196 47.47063135 43.81109569 55.47633984 54.01271122 48.44683889]
 [53.29309668 51.74462723 40.58428585 48.64070502 55.50143984 46.87925709]]


In [24]:
np.sort(ar4)

array([[47.30454397, 49.14024435, 49.16588355, 51.3191944 , 53.14240734,
        59.85420567],
       [43.81109569, 47.47063135, 48.44683889, 49.34184196, 54.01271122,
        55.47633984],
       [40.58428585, 46.87925709, 48.64070502, 51.74462723, 53.29309668,
        55.50143984]])

In [25]:
np.concatenate([ar1, ar2, ar3, ar4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
np.concatenate([ar2, ar4])

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [53.36416889, 54.80602927, 48.43250625, 42.43040169, 58.03485414,
        40.99687875],
       [44.29159807, 50.26520579, 57.6611818 , 55.52602102, 46.30812763,
        42.84829507],
       [56.37327844, 51.81222262, 45.49853033, 52.97080732, 48.98601635,
        41.91217136]])

In [27]:
print(ar3)
addarray = np.concatenate([ar2, ar4])
np.split(addarray, [3,7, 14])

[10 13 16 19]


[array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]]),
 array([[49.14024435, 53.14240734, 51.3191944 , 47.30454397, 59.85420567,
         49.16588355],
        [49.34184196, 47.47063135, 43.81109569, 55.47633984, 54.01271122,
         48.44683889],
        [53.29309668, 51.74462723, 40.58428585, 48.64070502, 55.50143984,
         46.87925709]]),
 array([], shape=(0, 6), dtype=float64),
 array([], shape=(0, 6), dtype=float64)]

In [28]:
np.min(ar3)

np.int64(10)

In [30]:
np.argmin(3)

np.int64(0)

In [31]:
print(ar3)
np.max(ar3)

[10 13 16 19]


np.int64(19)

In [32]:
print(ar3)
np.argmax(ar3)

[10 13 16 19]


np.int64(3)